### ISSUE TITLE
您好，想使用您的数据集，但没找到引用，请问能贴一下引用吗

### ISSUE THREAD

**Issue by GZU-JK** [SYF111/MCSH#1]

**Comment by SYF111** [comment]
https://github.com/SYF111/MCSH




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SYF111/MCSH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [SYF111/MCSH] 您好，想使用您的数据集，但没找到引用，请问能贴一下引用吗 (Issue #1)





 
Closed #1 as not planned.
